### ISSUE TITLE
"Shift" feature for Slide Animation Keys

### ISSUE THREAD

**Issue by Butterfish** [assumptionsoup/guppy_animation_tools#3]
I love using Slide Animation Keys!  I use it all the time in my animation workflow.  

I'm wondering if you can add another mode to the GUI?  I'm thinking it could be called Shift, and it would move the keys as a group to match the first selected key to the value of the prior unselected key, or the last selected key to the value of the next unselected key.  This way you can adjust poses without losing animation.     As another example, it basically is the same as moving all of the keys by +-n, where n is the difference between the first selected key in the group and the unselected key immediately prior to the group. 

If you need additional information, let me know.

**Comment by assumptionsoup** [comment]
Feature is in the qt_revamp branch. It will eventually get released once that branch is ready for prime time.
